[plugin]
id = "graphql-compiler-plugin"
class = "io.ballerina.stdlib.graphql.compiler.GraphqlCompilerPlugin"

[[dependency]]
<<<<<<< HEAD
path = "../graphql-compiler-plugin/build/libs/graphql-compiler-plugin-0.2.0-alpha8-SNAPSHOT.jar"
=======
path = "../graphql-compiler-plugin/build/libs/graphql-compiler-plugin-@project.version@.jar"
>>>>>>> 83ecd2b0be4f92b2c6de5cec10f2dd8758cbc0ac
